WsFederationPoC/Controllers/ApiCallController.cs
using System.Web.Mvc;

namespace WsFederationPoC.Controllers
{
    [Authorize]
    public class ApiCallController : Controller
    {
        // GET: ApiCall
        public ActionResult Index()
        {
            ViewBag.RemoteAppUrl =
                $"{Request.Url.Scheme}://{Request.Url.DnsSafeHost}:{Request.Url.Port}{Request.ApplicationPath}";
            return View();
        }
    }
}

WsFederationPoC/Controllers/CookieController.cs
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.DataHandler;
using WsFederationPoC.Models;

namespace WsFederationPoC.Controllers
{
    public class CookieController : Controller
    {
        // GET: Cookie
        public ActionResult Index()
        {
            var ticket = GetAuthenticationTicketFromCookie(HttpContext);

            ViewBag.Ticket = ticket;

            return View();
        }

        // https://long2know.com/2016/05/extracting-bearer-token-from-owin-cookie/
        public static AuthenticationTicket GetAuthenticationTicketFromCookie(HttpContextBase context)
        {
            var cookie = context.Request.Cookies.Get("WsFederationPoC");
            var ticket = cookie.Value;
            // Deal with URL encoding
            ticket = ticket.Replace('-', '+').Replace('_', '/');
            var padding = 3 - (ticket.Length + 3) % 4;
            if (padding != 0) ticket = ticket + new string('=', padding);
            var secureDataFormat = new TicketDataFormat(new MachineKeyProtector("cookie"));
            return secureDataFormat.Unprotect(ticket);
        }
    }
}

WsFederationPoC/Views/Shared/_Layout.cshtml
@using System.Threading
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=100" />
    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/fabric.min.js"></script>
    <script src="~/Scripts/spcontext.js"></script>
    <script src="~/Scripts/bundle.js"></script>
    <script src="~/Scripts/app.js"></script>
    <link href="~/Content/fabric.min.css" rel="stylesheet" />
    <link href="~/Content/fabric.components.min.css" rel="stylesheet" />
</head>
<body>
    <div class="ms-Pivot ms-Pivot--large">
        <ul class="ms-Pivot-links">
            <li class="ms-Pivot-link @( ViewBag.Current == "Home"? "is-selected" : "")" data-content="files" title="Home" tabindex="1">
                @Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "ms-Link" })
            </li>
            <li class="ms-Pivot-link @( ViewBag.Current == "Setup"? "is-selected" : "")" data-content="recent" title="Setup" tabindex="1">
                @Html.ActionLink("Setup", "Setup", "Home", new { }, new { @class = "ms-Link" })
            </li>
            <li class="ms-Pivot-link @( ViewBag.Current == "Api Call"? "is-selected" : "")" data-content="shared" title="Api Call" tabindex="1">
                @Html.ActionLink("Api Call", "Index", "ApiCall", new { }, new { @class = "ms-Link" })
            </li>
            @if (Thread.CurrentPrincipal.Identity.IsAuthenticated)
            {
                <li class="ms-Pivot-link" tabindex="1">
                    @Html.ActionLink("Logout", "LogOff", "Home", new { }, new { @class = "ms-Link" })
                </li>
                <li class="ms-Pivot-link @( ViewBag.Current == "Decode Cookie"? "is-selected" : "")" tabindex="1">
                    @Html.ActionLink("Decode Auth Cookie", "Index", "Cookie", new { }, new { @class = "ms-Link" })
                </li>
            }
        </ul>
    </div>
    @*<div class="ms-CommandBar">
            <span class="ms-font-m">
                @Html.ActionLink("Home", "Index", "Home")
            </span>
            <span class="ms-font-m">
                @Html.ActionLink("Setup", "Setup", "Home")
            </span>
            <span class="ms-font-m">
                @Html.ActionLink("Api Call", "Index", "ApiCall")
            </span>

            @if (Thread.CurrentPrincipal.Identity.IsAuthenticated)
            {
                <span class="ms-font-m">
                    @Html.ActionLink("Logout", "LogOff", "Home")
                </span>
                <span class="ms-font-m">
                    @Html.ActionLink("Decode Auth Cookie", "Index", "Cookie")
                </span>
            }
        </div>*@

    @RenderBody()


    @RenderSection("scripts", false)

</body>
</html>